name: Docker Image Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    permissions:
        contents: read
        packages: write
    runs-on: ubuntu-latest
    steps:
    - id: lower-repo
      name: Lowercase Repository Name
      run: |
        echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
    - name: Build Docker Image
      working-directory: ${{ github.workspace }}
      run: docker build . --tag ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker Image
      run: docker push ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest
  ssh_droplet_update:
    needs: build_and_push_image
    name: SSH to Droplet and Update Docker
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: api.unicycleunicorn.net
          username: root
          password: ${{ secrets.droplet_password }}
          script: docker compose pull && docker compose up -d && exit
